load("@rules_go//go:def.bzl", "go_library")

go_library(
  name = "klines",
  srcs = ["listklines.go"],
  deps = ["//BinanceAPI/common:common"],
  importpath = "github.com/Makoto2024/BinanceTrader/BinanceAPI/klines",
  visibility = ["//visibility:public"],
)