load("@rules_go//go:def.bzl", "go_library")

go_library(
  name = "storage",
  srcs = ["klinecsv.go"],
  deps = ["//BinanceAPI/klines:klines"],
  importpath = "github.com/Makoto2024/BinanceTrader/BinanceAPI/storage",
  visibility = ["//visibility:public"],
)