load("@rules_go//go:def.bzl", "go_library")

go_library(
  name = "common",
  srcs = [
      "endpoint.go",
      "enums.go",
      "parse.go",
  ],
  importpath = "github.com/Makoto2024/BinanceTrader/BinanceAPI/common",
  visibility = ["//visibility:public"],
)